### PR TITLE
Fix locale generation

### PR DESCRIPTION
**Pull request by Flohack74**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
It appears this is failing to build because `vivid` is the newest version in the Changelog. If you fix that, this should build correctly.

**Comment by UniversalSuperBox** [comment]
Somehow we ended up with `17.3.21` of `indicator-session` in our xenial repository, causing devices to have "Ubuntu help" rather than "UBports help" and other similar old issues. I've now made our version much newer to avoid this situation in the future.

**Comment by Flohack74** [comment]
Should we bring this in somehow? It seems okish, and only a packaging change

**Review by UniversalSuperBox — APPROVED** [review]
Yes. I probably did not approve this before because it was close to OTA-12 release.

**Comment by Flohack74** [comment]
by the way how to test this, where is indicator-session actually ^^

**Comment by UniversalSuperBox** [comment]
It's the farthest right indicator and it only shows in the indicator bar on wide shells. It can be found normally by going to the farthest right indicator.

**Comment by Flohack74** [comment]
Ok got it. So now that does not work at all: We do not have a pot file in the po directory, so I cannot link it to Weblate and we cannot update new strings. Its magic how every indicator has a different build setup...

**Comment by Flohack74** [comment]
Added #6 to rectifiy that.

**Pull request merged**
